Process Process-2:
Traceback (most recent call last):
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "swm_controller.py", line 192, in slave_routine
    r_gen = RolloutGenerator(logdir, device, time_limit)
  File "swm_controller.py", line 94, in __init__
    self.model.load_state_dict(torch.load(model_file))
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/serialization.py", line 857, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/serialization.py", line 846, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/serialization.py", line 157, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/_utils.py", line 79, in _cuda
    return new_type(self.size()).copy_(self, non_blocking)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/cuda/__init__.py", line 606, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
